# Generated by Django 3.0.5 on 2020-05-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('afterSchool', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FSSClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('abbr', models.CharField(max_length=10)),
                ('block', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('students', models.ManyToManyField(to='manageClasses.Student')),
                ('teachers', models.ManyToManyField(to='manageClasses.Teacher')),
            ],
        ),
    ]
